/* LENS CORE STUDIO V0.6 — identidade, planos assinados e proteção de dados. */
let lensMeta=null,lensShots=[],lensLoadedMode='',lensInitPromise=null,lensBackupWarning='',lensCandidate=null,lensVerifiedLicenses=[],lensRestoreRunning=false,lensSelectedPlan=1;
const lensTypes={daily:'Diário',weekly:'Semanal',monthly:'Mensal',manual:'Manual',safety:'Antes de restaurar'};
const lensLimits={daily:7,weekly:4,monthly:6,manual:5,safety:3};
function lensGet(k){return new Promise((resolve,reject)=>{const tx=db.transaction('vault'),r=tx.objectStore('vault').get(k);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
function lensPut(k,value){return new Promise((resolve,reject)=>{const tx=db.transaction('vault','readwrite');tx.objectStore('vault').put(value,k);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Falha ao gravar.'))})}
async function lensSaveMeta(){await lensPut('lens-meta-'+mode,lensMeta)}
async function lensHash(value){const b=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(value))));return Array.from(b,x=>x.toString(16).padStart(2,'0')).join('')}
function lensPeriods(date=new Date()){const day=localDate(date),monday=new Date(date.getFullYear(),date.getMonth(),date.getDate(),12);monday.setDate(monday.getDate()-((monday.getDay()+6)%7));return {daily:day,weekly:localDate(monday),monthly:day.slice(0,7)}}
async function lensInit(){if(!state)return;if(lensLoadedMode===mode&&lensMeta)return;if(lensInitPromise)return lensInitPromise;const current=mode;lensInitPromise=(async()=>{let m=await lensGet('lens-meta-'+current);if(!m){const bytes=crypto.getRandomValues(new Uint8Array(12));m={device:'LC-'+Array.from(bytes,x=>x.toString(16).padStart(2,'0')).join('').toUpperCase(),trialStart:0,tokens:[],lastExport:'',lastFileTest:'',lastRestore:''};await lensPut('lens-meta-'+current,m)}if(!/^LC-[A-F0-9]{24}$/.test(m.device)||!Array.isArray(m.tokens)||!Number.isFinite(m.trialStart))throw Error('Identificação local inválida. Preserve seus backups e contate o suporte.');lensMeta=m;lensShots=await lensGet('lens-shots-'+current)||[];lensVerifiedLicenses=[];for(const code of m.tokens){try{lensVerifiedLicenses.push(await lensVerify(code,m.device))}catch{}}lensLoadedMode=current;})().finally(()=>lensInitPromise=null);return lensInitPromise}
function lensStatus(){if(mode==='demo')return {kind:'demo',label:'Demonstração',end:0};if(!lensMeta)return {kind:'loading',label:'Verificando acesso',end:0};const now=Date.now(),valid=lensVerifiedLicenses.filter(p=>Date.parse(p.start)<=now&&Date.parse(p.end)>now).sort((a,b)=>Date.parse(b.end)-Date.parse(a.end));if(valid.length)return {kind:'pro',label:'PRO ativo',end:Date.parse(valid[0].end)};if(!lensMeta.trialStart)return {kind:'pending',label:'Teste aguardando cadastro',end:0};const end=lensMeta.trialStart+30*86400000;return now<end?{kind:'trial',label:'Teste gratuito',end}:{kind:'expired',label:'Modo de consulta',end}}
function lensCanEdit(){const k=lensStatus().kind;return k==='demo'||k==='pro'||k==='trial'||k==='pending'}
function lensDate(v){return v?new Date(v).toLocaleDateString('pt-BR'):'Ainda não realizado'}
async function lensSnapshot(type='manual'){if(!state||!record)return;const types=type==='auto'?['daily','weekly','monthly']:[type],periods=lensPeriods(),pack=await encode(state),hash=await lensHash(pack),now=new Date().toISOString();let all=await lensGet('lens-shots-'+mode)||[];for(const t of types){if(type==='auto'&&all.some(s=>s.type===t&&s.period===periods[t]))continue;all.push({id:uid(),type:t,period:periods[t]||now,at:now,hash,record:pack})}all=all.sort((a,b)=>b.at.localeCompare(a.at));const counts={};all=all.filter(s=>(counts[s.type]=(counts[s.type]||0)+1)<=(lensLimits[s.type]||3));await lensPut('lens-shots-'+mode,all);lensShots=all;lensBackupWarning=''}
async function lensAutomatic(){try{await lensSnapshot('auto')}catch{lensBackupWarning='Os dados foram salvos, mas a cópia automática falhou. Exporte um backup e confira o espaço disponível.'}}
const lensOriginalCommit=commit;
commit=async function(fn,label){await lensInit();if(!lensRestoreRunning&&!lensCanEdit())throw Error('Seu período terminou. Você pode consultar e exportar seus dados. Ative o Plano PRO para voltar a editar.');const result=await lensOriginalCommit(fn,label);await lensAutomatic();return result};
const lensEnter=enter;enter=async function(m){lensMeta=null;lensLoadedMode='';lensVerifiedLicenses=[];lensShots=[];await lensEnter(m);if(state){await lensInit();await lensAutomatic();render()}};
function lensBrandMarkup(){return `<img class="lens-brand" src="${LENS_BRAND.dark}" alt="LENS CORE STUDIO">`}
const lensWelcome=welcome;welcome=function(){return lensWelcome().replace(/<div class="brand"><div class="brand-mark"><\/div><div>[\s\S]*?<\/div><\/div>/,`<div class="brand lens-welcome-brand">${lensBrandMarkup()}</div>`).replaceAll('LUME','LENS CORE')};
const lensShell=shell;shell=function(content){const st=lensStatus();let h=lensShell(content).replace(/<div class="brand"><div class="brand-mark"><\/div><div>[\s\S]*?<\/div><\/div>/,`<div class="brand lens-sidebar-brand">${lensBrandMarkup()}</div>`);if(mode==='demo')h=h.replaceAll('LUME Studio','LENS CORE STUDIO');h=h.replace('<main class="main">',`<main class="main">${mode!=='demo'&&st.kind==='expired'?`<div class="lens-notice"><b>Seu período de acesso terminou.</b><span>Seus dados continuam disponíveis para consulta e backup.</span>${btn('Ativar Plano PRO','nav:pro','shield','primary')}</div>`:''}${lensBackupWarning?`<p class="form-error">${esc(lensBackupWarning)}</p>`:''}`);return h};
const lensSettings=settingsPage;settingsPage=function(){return lensSettings()+`<section class="section grid cols2"><div class="card"><h2>Backup e proteção</h2><p>Cópias diárias, semanais e mensais, exportação e restauração conferida.</p>${btn('Abrir central de backup','nav:protection','shield','primary')}</div><div class="card"><h2>LENS CORE STUDIO PRO</h2><p>${lensStatus().label} · planos a partir de ${money(8990)}/mês.</p>${btn('Ver planos e ativar','nav:pro','shield','primary')}</div></section><p class="legend">LENS CORE STUDIO · V${VERSION}</p>`};
const lensMore=morePage;morePage=function(){return lensMore().replace('<div class="more-grid uniform-more">',`<div class="more-grid uniform-more"><button class="card more-card" data-action="nav:protection">${icon('shield')}<span class="grow"><b>Backup e proteção</b><small class="block">Cópias automáticas e restauração</small></span>${icon('arrow')}</button><button class="card more-card" data-action="nav:pro">${icon('shield')}<span class="grow"><b>Plano PRO</b><small class="block">Planos, validade e código de ativação</small></span>${icon('arrow')}</button>`)};
routeCovers.protection='archive';routeCovers.pro='capture';
navs.push(['protection','Backup e proteção','shield'],['pro','Plano PRO','shield']);
function lensProPage(){const st=lensStatus();return header('Plano PRO','Mais tempo para criar. Seu estúdio organizado.')+`<section class="card lens-pro-status"><img src="${LENS_BRAND.light}" class="lens-pro-logo" alt="LENS CORE STUDIO"><div><span class="soft-chip tone-cash">${st.label}</span><h2>${st.kind==='demo'?'Explore o estúdio':st.kind==='pro'?'Seu estúdio está no PRO':st.kind==='trial'?'30 dias para conhecer todos os recursos':st.kind==='pending'?'Complete seu cadastro para iniciar os 30 dias':'Continue sua produção com o PRO'}</h2><p>${st.end?'Validade: '+new Date(st.end).toLocaleString('pt-BR'):st.kind==='pending'?'A contagem só começa quando o perfil do estúdio for salvo.':'A demonstração não exige ativação.'}</p><p class="note">${mode==='demo'?'Para ativar uma licença, entre no seu estúdio real.':st.kind==='pending'?'Você não perde nenhum dia do teste antes de concluir o cadastro.':'Após o vencimento, os dados permanecem disponíveis para consulta e backup.'}</p></div></section><div class="lens-plan-grid section">${Object.values(LENS_PLANS).map(p=>{const base=p.months*8990,save=base-p.total;return `<button class="card lens-plan ${lensSelectedPlan===p.months?'selected':''}" data-action="lens-plan:${p.months}" aria-pressed="${lensSelectedPlan===p.months}"><span>${p.label} · ${p.months} ${p.months===1?'mês':'meses'}</span><strong>${money(p.total)}</strong><b>${p.months===1?'Por mês':money(p.total/p.months)+'/mês equivalente'}</b><small>${save?'Economia de '+money(save)+' ('+Math.round(save/base*100)+'%)':'Sem compromisso semestral ou anual'}</small><small>${p.months===1?'Ativação por 1 mês':'Valor total do período · pagamento único'}</small></button>`}).join('')}</div><section class="card section"><h2>Solicitar ou renovar</h2><p>Escolha o plano e envie seu ID pelo WhatsApp. A liberação acontece com o código enviado após a confirmação do pagamento pelo atendimento.</p><label class="compact-label">ID deste navegador/aparelho<input readonly value="${esc(lensMeta?.device||'Carregando…')}" class="lens-device"></label><div class="row wrap section">${btn('Copiar ID','lens-copy-id','copy')}${btn('Solicitar pelo WhatsApp · (11) 95352-5141','lens-request','phone','primary')}</div><p class="legend">Celular e desktop têm IDs independentes. Não há cobrança automática nem sincronização entre aparelhos.</p></section><section class="card section"><h2>Já tenho meu código</h2><label>Código de ativação<textarea id="lens-code" spellcheck="false" placeholder="Cole o código completo LCS1…" rows="4"></textarea></label>${btn('Ativar Plano PRO','lens-activate','check','primary')}<p id="lens-pro-error" class="form-error" role="alert"></p>${lensVerifiedLicenses.length?'<p class="note">Licenças registradas: '+lensVerifiedLicenses.map(p=>`${p.months} meses · ${lensDate(p.start)} a ${lensDate(p.end)}`).join(' / ')+'</p>':''}</section>`}
function lensProtectionPage(){return header('Backup e proteção','Proteja os registros e as histórias do seu estúdio.')+`<div class="grid cols3"><section class="card"><h2>Cópias locais</h2><p>Geradas na primeira abertura ou gravação de cada período.</p>${['daily','weekly','monthly'].map(t=>`<div class="between"><span>${lensTypes[t]}</span><b>${lensShots.filter(s=>s.type===t).length}/${lensLimits[t]}</b></div>`).join('')}<p class="legend">Funcionam enquanto o app está aberto. Ficam neste navegador e não substituem um arquivo guardado fora dele.</p></section><section class="card"><h2>Arquivo externo</h2><p>Última geração: <b>${lensDate(lensMeta?.lastExport)}</b></p><p class="legend">Confira o arquivo na pasta de downloads e guarde uma cópia em local seguro.</p>${btn('Exportar backup','backup','download','primary')}</section><section class="card"><h2>Conferência e recuperação</h2><p>Último arquivo testado: <b>${lensDate(lensMeta?.lastFileTest)}</b></p><p>Última restauração: <b>${lensDate(lensMeta?.lastRestore)}</b></p>${btn('Conferir / restaurar arquivo','restore','shield')}</section></div><section class="card section"><div class="between wrap"><div><h2>Pontos de restauração</h2><p>As cópias respeitam a senha local. Uma cópia antiga pode exigir a senha usada quando foi criada.</p></div>${btn('Criar ponto agora','lens-snapshot','plus','primary')}</div>${lensShots.map(s=>`<article class="lens-snapshot"><div><b>${lensTypes[s.type]||'Cópia'}</b><small>${new Date(s.at).toLocaleString('pt-BR')} · ${s.record.encrypted?'Protegido por senha':'Sem senha'}</small></div><div class="row wrap">${btn('Conferir','lens-inspect:'+s.id,'shield')}${btn('Excluir','lens-delete-shot:'+s.id,'trash','danger')}</div></article>`).join('')||empty('Nenhuma cópia ainda','Crie um ponto para proteger seus registros.')}</section><p class="notice">A restauração substitui os dados do espaço aberto e cria antes uma cópia de segurança. Licença e ID deste aparelho são mantidos. Backups antigos do LUME continuam aceitos.</p>`}
const lensRender=render;render=function(){if(state&&route==='pro'){$('#app').innerHTML=shell(lensProPage());return}if(state&&route==='protection'){$('#app').innerHTML=shell(lensProtectionPage());return}return lensRender()};
async function lensBackupPack(){const data=await encode(validate(structuredClone(state))),p={format:'LensCoreBackup',version:1,appVersion:VERSION,source:mode,exportedAt:new Date().toISOString(),record:data};p.hash=await lensHash(p.record);return p}
backup=async function(){await lensInit();const p=await lensBackupPack(),raw=JSON.stringify(p);if(await lensHash(JSON.parse(raw).record)!==p.hash)throw Error('A verificação do backup falhou.');download('LENSCORE-'+mode+'-'+today()+'.lcsbak',raw,'application/json');lensMeta.lastExport=new Date().toISOString();await lensSaveMeta();toast('Backup gerado e conferido. Confira o download.');render()};
async function lensDecodePack(p,pass=''){if(!p||!['LensCoreBackup','LumeBackup'].includes(p.format)||p.version!==1||!p.record)throw Error('Este arquivo não é um backup compatível do estúdio.');if(p.source!==mode)throw Error('Abra o espaço '+(p.source==='demo'?'de demonstração':'real')+' para conferir esse backup.');if(p.format==='LensCoreBackup'&&(!p.hash||p.hash!==await lensHash(p.record)))throw Error('O arquivo foi alterado ou está corrompido.');let data;if(p.record.encrypted){if(!pass)throw Error('Informe a senha usada nessa cópia.');try{const k=await derive(pass,p.record.salt);data=await decode(p.record,k)}catch{throw Error('Senha incorreta ou cópia danificada.')}}else data=validate(structuredClone(p.record.data));return validate(data)}
function lensRestoreForm(snapshot=''){modal('Conferir backup',`<p>Primeiro vamos validar a cópia e mostrar os registros encontrados. Seus dados atuais só serão substituídos após a confirmação.</p><input name="snapshot" type="hidden" value="${esc(snapshot)}">${snapshot?'':'<label>Arquivo de backup<input type="file" name="backupFile" accept=".lcsbak,.lumebak,.json,application/json" required></label>'}<label>Senha usada no backup (se houver)<input type="password" name="backupPassword" autocomplete="off"></label>`,'lens-inspect-backup','Conferir arquivo')}
async function lensInspect(p,pass){const data=await lensDecodePack(p,pass);lensCandidate={data,at:p.exportedAt,source:mode,revision};lensMeta.lastFileTest=new Date().toISOString();await lensSaveMeta();modal('Backup conferido',`<p class="notice">Estrutura e vínculos conferidos${p.format==='LensCoreBackup'?' · integridade SHA-256 conferida':''}.</p><p>${data.clients.length} clientes · ${data.projects.length} trabalhos · ${data.events.length} compromissos · ${data.transactions.length} lançamentos · ${data.quotes.length} propostas</p><p>Cópia de ${lensDate(p.exportedAt)}. Restaurar substituirá os dados atuais deste espaço.</p><p class="legend">Uma cópia de segurança dos dados atuais será criada antes da substituição.</p><div class="row wrap">${btn('Somente conferir e fechar','close')}${btn('Restaurar esta cópia','lens-confirm-restore','shield','primary')}</div>`)}
async function lensRestore(){if(!lensCandidate||lensCandidate.source!==mode)throw Error('Confira o arquivo novamente.');if(revision!==lensCandidate.revision)throw Error('Os dados mudaram após a conferência. Confira o backup novamente.');await lensSnapshot('safety');const data=structuredClone(lensCandidate.data);lensRestoreRunning=true;try{await commit(d=>{for(const k of Object.keys(d))delete d[k];Object.assign(d,data)},'Backup restaurado');lensMeta.lastRestore=new Date().toISOString();await lensSaveMeta();lensCandidate=null;closeModal(true);go('protection');toast('Restauração concluída. A cópia anterior está na central.')}finally{lensRestoreRunning=false}}
const lensSubmit=submit;submit=async function(kind,f){if(kind==='lens-inspect-backup'){await lensInit();const v=Object.fromEntries(new FormData(f));let p;if(v.snapshot){const s=lensShots.find(s=>s.id===v.snapshot);if(!s)throw Error('Cópia não encontrada.');p={format:'LensCoreBackup',version:1,record:s.record,hash:s.hash,source:mode,exportedAt:s.at}}else{const file=f.querySelector('[name=backupFile]').files[0];if(!file||file.size>32000000)throw Error('Selecione um backup de até 32 MB.');try{p=JSON.parse(await file.text())}catch{throw Error('Arquivo ilegível.')}}await lensInspect(p,v.backupPassword);return}if(state&&mode!=='demo'&&!['unlock','password'].includes(kind)){await lensInit();if(!lensCanEdit())throw Error('Ative o Plano PRO para editar. Consulta e backup continuam disponíveis.')}const result=await lensSubmit(kind,f);if(kind==='unlock'&&state){await lensInit();await lensAutomatic();render()}return result};
const lensAction=action;action=async function(a){const [cmd,id]=a.split(':');if(cmd==='lens-copy-id'){await lensInit();try{await navigator.clipboard.writeText(lensMeta.device);toast('ID copiado.')}catch{modal('Copiar ID',`<input readonly value="${lensMeta.device}"><p>Selecione e copie o ID acima.</p>`)}return}if(cmd==='lens-plan'){lensSelectedPlan=Number(id);render();return}if(cmd==='lens-request'){await lensInit();if(mode==='demo')throw Error('Entre no seu estúdio real para solicitar uma licença.');const p=LENS_PLANS[lensSelectedPlan],st=lensStatus(),msg=`Olá! Gostaria de solicitar o Plano PRO do LENS CORE STUDIO.\nPlano: ${p.label} (${p.months} meses)\nValor total: ${money(p.total)}\nID: ${lensMeta.device}\n${st.kind==='pro'?'Validade atual: '+new Date(st.end).toISOString()+'\n':''}Por favor, envie as orientações de pagamento e ativação.`;window.open('https://wa.me/'+LENS_SUPPORT+'?text='+encodeURIComponent(msg),'_blank','noopener');return}if(cmd==='lens-activate'){await lensInit();if(mode==='demo')throw Error('Ative no estúdio real, fora da demonstração.');const code=$('#lens-code').value.trim();try{const p=await lensVerify(code,lensMeta.device);if(Date.parse(p.end)<=Date.now())throw Error('Este código já venceu.');if(lensVerifiedLicenses.some(x=>x.id===p.id))throw Error('Este código já foi utilizado.');const next={...lensMeta,tokens:[...lensMeta.tokens,code]};await lensPut('lens-meta-'+mode,next);lensMeta=next;lensVerifiedLicenses.push(p);render();toast(Date.parse(p.start)>Date.now()?'Licença registrada. Será válida a partir de '+lensDate(p.start):'Plano PRO ativado.')}catch(e){$('#lens-pro-error').textContent=e.message}return}if(cmd==='lens-snapshot'){await lensSnapshot();render();toast('Ponto de restauração criado.');return}if(cmd==='lens-inspect')return lensRestoreForm(id);if(cmd==='lens-delete-shot'){if(!confirm('Excluir somente este ponto de restauração?'))return;const next=lensShots.filter(s=>s.id!==id);await lensPut('lens-shots-'+mode,next);lensShots=next;render();return}if(cmd==='lens-confirm-restore')return lensRestore();if(cmd==='restore')return lensRestoreForm();if(cmd==='close')lensCandidate=null;if(cmd==='nav'&&['pro','protection'].includes(id)){await lensInit();if(id==='protection')lensShots=await lensGet('lens-shots-'+mode)||[];}return lensAction(a)};

const lensDocumentHTML=documentHTML;documentHTML=function(kind,item){return lensDocumentHTML(kind,item).replace('</body>',`<footer style="margin-top:20px;border-top:1px solid #ccc;padding-top:10px"><img src="${LENS_BRAND.signature}" alt="Documento gerado pelo LensCore Studio" style="width:190px;height:auto"></footer></body>`)};
printQuote=function(pid){const p=project(pid);if(!p)throw Error('Trabalho não encontrado.');return openPDF('quote',{title:p.name,clientId:p.clientId,amount:p.value,validUntil:addDays(15),eventDate:p.date,deliveryDate:p.due,location:p.location,scope:p.brief||'Escopo a definir.',paymentTerms:'Condições a combinar com o cliente.'})};

/* V0.6.2 — instalação, onboarding, teste pós-cadastro e demonstração controlada. */
let lensInstallPrompt=null;
const lensDemoKinds={client:'clientes',project:'trabalhos',event:'compromissos',transaction:'lançamentos',gear:'equipamentos',quote:'propostas',contract:'contratos',partner:'fornecedores e parceiros',assignment:'custos de equipe',installments:'planejamentos de parcelas'};
const lensTutorialSteps=[
 {route:'home',title:'Inicial',text:'Seu painel de partida reúne os atalhos principais e os avisos que pedem atenção.',items:['Crie trabalhos, propostas, compromissos e clientes','Acompanhe alertas pelo sino do cabeçalho']},
 {route:'agenda',title:'Agenda',text:'Organize sessões, reuniões, entregas e lembretes em diferentes períodos.',items:['Alterne entre dia, semana, quinzena, mês e trimestre','Abra, edite e conclua compromissos']},
 {route:'projects',title:'Trabalhos',text:'Acompanhe cada produção do primeiro contato até a entrega.',items:['Use etapas, capas e progresso visual','Controle tarefas, entregas, equipe e valores']},
 {route:'clients',title:'Clientes',text:'Centralize dados de pessoas e empresas e agilize o contato.',items:['Cadastre CPF ou CNPJ e endereço','Envie mensagens pelo WhatsApp']},
 {route:'finance',title:'Financeiro',text:'Veja o que entrou, o que saiu, o que falta receber e a margem por trabalho.',items:['Registre recebimentos, despesas e estornos','Planeje parcelas e acompanhe vencimentos']},
 {route:'quotes',title:'Propostas e contratos',text:'Prepare documentos profissionais com os dados e a identidade do estúdio.',items:['Monte serviços e condições detalhadas','Gere PDF A4 com logo e assinatura LensCore']},
 {route:'partners',title:'Fornecedores e parceiros',text:'Cadastre sua rede de apoio e vincule custos às produções.',items:['Organize contatos e especialidades','Leve custos contratados ao financeiro do trabalho']},
 {route:'gear',title:'Equipamentos',text:'Mantenha o kit do estúdio identificado e com situação atualizada.',items:['Cadastre câmeras, lentes, áudio e iluminação','Marque itens em uso ou manutenção']},
 {route:'protection',title:'Backup e proteção',text:'Crie cópias, confira arquivos e restaure seus registros com segurança.',items:['Use pontos automáticos e manuais','Exporte uma cópia para outro local']},
 {route:'pro',title:'Plano PRO',text:'Consulte o teste gratuito, os planos e a ativação deste aparelho.',items:['O teste real dura 30 dias após o cadastro','Cada aparelho possui um ID de ativação']},
 {route:'settings',title:'Configurações',text:'Ajuste identidade, segurança, instalação e preferências do estúdio.',items:['Adicione seu logo aos PDFs','Instale o app e retome este tutorial quando quiser']}
];
function lensInstalled(){return (typeof matchMedia==='function'&&matchMedia('(display-mode: standalone)').matches)||navigator.standalone===true}
function lensIOS(){return /iphone|ipad|ipod/i.test(navigator.userAgent)}
function lensReadJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function lensWriteJSON(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function lensDemoUsage(){return lensReadJSON('lens-demo-creates-v1',{})}
function lensTutorialData(){return lensReadJSON('lens-tutorial-v1-'+mode,{active:false,index:0,completed:false})}
function lensSaveTutorial(value){lensWriteJSON('lens-tutorial-v1-'+mode,value)}
function lensTutorialDock(){const t=lensTutorialData(),s=lensTutorialSteps[t.index]||lensTutorialSteps[0];return t.active?`<aside class="lens-tutorial-dock" aria-live="polite"><div><small>TUTORIAL · ${t.index+1}/${lensTutorialSteps.length}</small><b>${esc(s.title)}</b></div>${btn('Continuar','lens-tutorial-show','arrow','primary')}${btn('Encerrar','lens-tutorial-exit','','secondary')}</aside>`:''}
function lensTutorialShow(index=lensTutorialData().index){index=Math.max(0,Math.min(lensTutorialSteps.length-1,Number(index)||0));const s=lensTutorialSteps[index],t={active:true,index,completed:false};lensSaveTutorial(t);modal('Tutorial guiado',`<div class="lens-tutorial-progress"><i style="width:${(index+1)/lensTutorialSteps.length*100}%"></i></div><p class="eyebrow">ETAPA ${index+1} DE ${lensTutorialSteps.length}</p><h2>${esc(s.title)}</h2><p>${esc(s.text)}</p><ul class="lens-tutorial-list">${s.items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="lens-tutorial-actions">${index?btn('Anterior','lens-tutorial-prev','arrow'):''}${btn('Ir para esta tela','lens-tutorial-go','arrow','copper')}${index<lensTutorialSteps.length-1?btn('Próxima','lens-tutorial-next','arrow','primary'):btn('Concluir tutorial','lens-tutorial-finish','check','primary')}</div><p class="legend">Você pode encerrar e retomar depois em Configurações.</p>`)}
function lensStartTutorial(force=false){const t=lensTutorialData();if(force||!t.completed){lensSaveTutorial({active:true,index:force?0:t.index||0,completed:false});lensTutorialShow(force?0:t.index||0)}}
function lensInstallHelp(){const text=lensIOS()?'No Safari, toque em Compartilhar e depois em “Adicionar à Tela de Início”.':'Abra o menu do navegador e escolha “Instalar aplicativo” ou “Adicionar à tela inicial”.';modal('Instalar LENS CORE STUDIO',`<div class="lens-install-guide">${lensBrandMarkup()}<h2>Tenha o estúdio a um toque</h2><p>${text}</p><p class="note">Depois de instalado, o app ganha ícone próprio e abre em uma janela independente. Seus registros continuam salvos neste navegador e dispositivo.</p></div>`)}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();lensInstallPrompt=e;if(state&&route==='settings')render()});
window.addEventListener('appinstalled',()=>{lensInstallPrompt=null;try{localStorage.setItem('lens-installed','1')}catch{};if(state)render();toast('LENS CORE STUDIO instalado com sucesso.')});

const lensWelcome62=welcome;
welcome=function(){let h=lensWelcome62();const install=lensInstalled()?`<div class="lens-install-ready">${icon('check')} Aplicativo instalado neste dispositivo</div>`:btn('Instalar LENS CORE STUDIO','lens-install','download','primary');return h.replace('<small>Seus registros',`<div class="lens-welcome-install">${install}</div><small>Seus registros`)};
const lensShell62=shell;
shell=function(content){let h=lensShell62(content),tools=`<div class="lens-header-tools">${mode==='demo'?btn('SAIR DO MODO DEMONSTRAÇÃO','exit','logout','lens-demo-exit'):''}${btn('Tutorial','lens-tutorial-show','info','lens-tutorial-button')}</div>`;h=h.replace('<header class="topbar">',`<header class="topbar">${tools}`);h=h.replace('<nav class="mobile-nav"',lensTutorialDock()+'<nav class="mobile-nav"');if(mode==='demo'){const usage=lensDemoUsage(),used=Object.values(usage).reduce((a,b)=>a+Number(b||0),0);h=h.replace('<main class="main">',`<main class="main"><div class="lens-demo-rule"><b>Demonstração controlada</b><span>Até 2 novos cadastros por função · ${used} criações realizadas neste navegador.</span></div>`)}return h};
const lensSettings62=settingsPage;
settingsPage=function(){return lensSettings62()+`<section class="section grid cols2 lens-onboarding-settings"><div class="card"><h2>Instalar aplicativo</h2><p>${lensInstalled()?'Este dispositivo já abre o LENS CORE STUDIO como aplicativo.':'Instale no celular ou desktop para abrir com ícone e janela próprios.'}</p>${lensInstalled()?'<span class="soft-chip tone-income">Aplicativo instalado</span>':btn('Instalar LENS CORE STUDIO','lens-install','download','primary')}</div><div class="card"><h2>Tutorial guiado</h2><p>Conheça as telas e vá diretamente à função apresentada em cada etapa.</p>${btn(lensTutorialData().completed?'Refazer tutorial':'Iniciar ou retomar','lens-tutorial-start','info','primary')}</div></section>`};

const lensSubmit62=submit;
submit=async function(kind,f){if(state)await lensInit();const id=f?.querySelector?.('[name=id]')?.value||'',isNew=kind in lensDemoKinds&&!id;if(mode==='real'&&lensStatus().kind==='pending'&&!['profile','unlock','password','lens-inspect-backup'].includes(kind))throw Error('Complete o cadastro do estúdio para iniciar seus 30 dias gratuitos e liberar as funções.');if(mode==='demo'&&isNew){const usage=lensDemoUsage(),count=Number(usage[kind]||0);if(count>=2)throw Error(`O modo demonstração permite criar até 2 ${lensDemoKinds[kind]} novos. Saia da demonstração para continuar no seu estúdio.`)}const startsTrial=mode==='real'&&kind==='profile'&&lensMeta&&!lensMeta.trialStart;const result=await lensSubmit62(kind,f);if(mode==='demo'&&isNew){const usage=lensDemoUsage();usage[kind]=Number(usage[kind]||0)+1;lensWriteJSON('lens-demo-creates-v1',usage)}if(startsTrial){lensMeta.trialStart=Date.now();await lensSaveMeta();render();toast('Cadastro concluído: seus 30 dias gratuitos começaram agora.');setTimeout(()=>lensStartTutorial(true),250)}return result};
const lensAction62=action;
action=async function(a){const [cmd]=a.split(':');if(cmd==='lens-install'){if(lensInstalled()){toast('O aplicativo já está instalado neste dispositivo.');return}if(lensInstallPrompt){lensInstallPrompt.prompt();const choice=await lensInstallPrompt.userChoice;if(choice.outcome==='accepted')lensInstallPrompt=null;else toast('Instalação cancelada. Você pode tentar novamente.');return}return lensInstallHelp()}if(cmd==='lens-tutorial-start'){lensStartTutorial(true);return}if(cmd==='lens-tutorial-show'){lensTutorialShow();return}if(cmd==='lens-tutorial-prev'){const t=lensTutorialData();lensTutorialShow(t.index-1);return}if(cmd==='lens-tutorial-next'){const t=lensTutorialData();lensTutorialShow(t.index+1);return}if(cmd==='lens-tutorial-go'){const t=lensTutorialData(),s=lensTutorialSteps[t.index];closeModal(true);go(s.route);toast('Você está em '+s.title+'. Use “Continuar” para seguir o tutorial.');return}if(cmd==='lens-tutorial-exit'){lensSaveTutorial({...lensTutorialData(),active:false});closeModal(true);if(state)render();toast('Tutorial pausado. Retome em Configurações.');return}if(cmd==='lens-tutorial-finish'){lensSaveTutorial({active:false,index:lensTutorialSteps.length-1,completed:true});closeModal(true);render();toast('Tutorial concluído. Você pode refazê-lo quando quiser.');return}return lensAction62(a)};
boot();
